In [1]:
import seaborn as sns 
import pandas as pd 
import numpy as np 

In [3]:
df = pd.read_csv('datas/Advertising.csv')

In [5]:
df.head()

,Unnamed: 0,TV,Radio,Newspaper,Sales
0,1,230.1,37.8,69.2,22.1
1,2,44.5,39.3,45.1,10.4
2,3,17.2,45.9,69.3,9.3
3,4,151.5,41.3,58.5,18.5
4,5,180.8,10.8,58.4,12.9


In [7]:
# preprocessing Data and Polynomial Regression
X = df.drop('Sales', axis=1)
X = X.drop('Unnamed: 0' , axis = 1)

y = df['Sales']

In [ ]:
# A B A*b AA BB

In [9]:
from sklearn.preprocessing import PolynomialFeatures

In [11]:
polynomial_converter = PolynomialFeatures(
    degree=2,
    include_bias=False
)

In [13]:
polynomial_converter.fit(X)

PolynomialFeatures(include_bias=False)

In [15]:
poly_features = polynomial_converter.transform(X)

In [17]:
poly_features.shape

(200, 9)

In [19]:
X.shape

(200, 3)

In [21]:
poly_features[0]

array([2.301000e+02, 3.780000e+01, 6.920000e+01, 5.294601e+04,
       8.697780e+03, 1.592292e+04, 1.428840e+03, 2.615760e+03,
       4.788640e+03])

In [23]:
from sklearn.model_selection import train_test_split 

In [55]:
X_train , X_test , y_train , y_test = train_test_split(
    poly_features,
    y,
    test_size=0.4,
    random_state=101
)

In [57]:
from sklearn.linear_model import LinearRegression

In [59]:
model = LinearRegression(fit_intercept=True)

In [61]:
model.fit(X_train, y_train)

LinearRegression()

In [63]:
test_prediction = model.predict(X_test)

In [65]:
from sklearn.metrics import mean_absolute_error , mean_squared_error , r2_score

In [67]:
y.mean()

14.0225

In [69]:
mae = mean_absolute_error(y_test, test_prediction)

mse =mean_squared_error(y_test ,test_prediction)

r2 = r2_score(y_test, test_prediction)

r2

0.9858391678651933

In [85]:
model.coef_

array([ 5.15632511e-02,  2.51650376e-02,  1.74854029e-02, -1.08888997e-04,
        1.13923920e-03, -6.82208958e-05, -1.48386755e-04, -2.32829225e-05,
        1.96943486e-05])

In [81]:
# time to save our model

In [91]:
from joblib import dump , load

In [87]:
dump(model , 'advertising_model_polybominal.joblib')

['advertising_model_polybominal.joblib']

In [93]:
dump(polynomial_converter , 'poly_convertor.joblib')

['poly_convertor.joblib']

In [95]:
# load data 

In [107]:
campain = [[200 , 0 , 0 ]]

In [109]:
loaded_model = load('advertising_model_polybominal.joblib')
loaded_poly = load('poly_convertor.joblib')


In [111]:
campain_poly = loaded_poly.transform(campain)

C:\Users\micro\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but PolynomialFeatures was fitted with feature names
  warnings.warn(


In [113]:
campain_poly

array([[  200.,     0.,     0., 40000.,     0.,     0.,     0.,     0.,
            0.]])

In [115]:
loaded_model.predict(campain_poly)

array([10.88505368])